// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 26.11.2025, 23:37:34
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["E:/ITSchool/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ITSchool/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ITSchool/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ITSchool/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ITSchool/plugins/**/*.{js,ts,mjs}","E:/ITSchool/composables/**/*.{js,ts,mjs}","E:/ITSchool/utils/**/*.{js,ts,mjs}","E:/ITSchool/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/ITSchool/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/ITSchool/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/ITSchool/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;